image: monitor:5000/project-i-client

stages:
  - QA
  - deploy

validateHTML:
  stage: QA
  script:
    - ln -s /project/node_modules node_modules
    - npm run validate-html

sonar:
  stage: QA
  script:
    - ln -s /project/node_modules node_modules
    - chmod -R 755 /project/node_modules/sonar-scanner/bin
    - npm run validate-sonar

deploy:
  stage: deploy
  only:
    - main
  except:
    changes:
      - documents/**/*
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 172.18.18.201 >> ~/.ssh/known_hosts
    - scp -qr ./src/* gitlab-runner@172.18.18.201:"/var/www/html/2022-2023/battleship-${CI_PROJECT_NAMESPACE:(-2)}/"
  environment: production

